/**
 * Server Side Rendering
 */
import { APIGatewayEvent } from "aws-lambda";
import React from "react";
import { renderToString } from "react-dom/server";
import { StaticRouter } from "react-router-dom/server";
import App from "../browser/App";
import ConfigContext from "../components/ConfigContext";
import { buildDependencies } from "../components/di/Dependencies";
import { DependenciesContext } from "../components/di/DependenciesContext";
import config from "./config";
import html from "./html";
import { Stats } from "./types";

/** Whether we're running on a local desktop or on AWS Lambda */
const isLocal = process.env.IS_LOCAL || process.env.IS_OFFLINE;

/**
 * Server-side rendering
 */
export default async function render(event: APIGatewayEvent): Promise<string> {
  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
  const stats = (await import("../../dist/stats.json")) as unknown as Stats;
  const dependencies = buildDependencies(config.app.BACKEND_URL);

  const content = renderToString(
    <ConfigContext.Provider value={config}>
      <DependenciesContext.Provider value={dependencies}>
        <StaticRouter location="/login">
          <App />
        </StaticRouter>
      </DependenciesContext.Provider>
    </ConfigContext.Provider>,
  );
  return html({ stats, content, config });
}
